version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    # No depends_on needed since we're using localhost

  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    restart: unless-stopped