name: "3940-Lab-3"
services:
  frontend:
    container_name: 3940-Lab-3-frontend
    build: /frontend
    ports:
      - "3000:80"

  backend:
    container_name: 3940-Lab-3-backend
    build: /backend
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_HTTP_PORTS: 5000
      PostgresConnectionString: ${POSTGRES_CONNECTION_STRING}
      AllowedOrigins: ${ALLOWED_ORIGINS}