version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:5000/api  # Local dev URL
    restart: unless-stopped
    networks:
      - pokemon-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}  # Inherits from .env
    restart: unless-stopped
    networks:
      - pokemon-net

networks:
  pokemon-net:
    driver: bridge